export const FIND_EVENT_DATA = "FIND_EVENT_DATA"
export const UPDATE_EVENT = "UPDATE_EVENT"

export const CREATE_GUEST_INVITE = "CREATE_GUEST_INVITE"
export const UPDATE_GUEST_INVITE = "UPDATE_GUEST_INVITE"
export const DELETE_GUEST_INVITE = "DELETE_GUEST_INVITE"

export const CREATE_EVENT_TASK = "CREATE_EVENT_TASK"
export const UPDATE_EVENT_TASK = "UPDATE_EVENT_TASK"
export const DELETE_EVENT_TASK = "DELETE_EVENT_TASK"
