export const CREATE_REVIEW = "CREATE_REVIEW";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const FIND_ALL_REVIEWS = "FIND_ALL_REVIEWS";
export const FIND_ALL_REVIEWS_FOR_FOODID = "FIND_ALL_REVIEWS_FOR_FOODID";
export const FIND_ALL_REVIEWS_BY_USERID = "FIND_ALL_REVIEWS_BY_USERID";

